const GLOBAL_CONSTANTS = {
  VERSION: "v0.0.16",
  PORT: 3001,
  USER_DATABASE: "admin",
  PASS_DATABASE: "Hfy2020Db#",
  SERVER_DATABASE: "hfy-database-1.cuvtxvydqsnt.us-east-2.rds.amazonaws.com",
  DATABASE_NAME: "HOMIFYDBTEST",
  DATABASE_PORT: 1433,
  MASTER_KEY_PERMISSION: "HfyAuth2020Db#",
  ACCESS_KEY_ID: "AKIAJZ2VBYROHPNFRTKA",
  SECRET_ACCESS_KEY: "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",
};

module.exports = GLOBAL_CONSTANTS;
